# Dataset Configuration
YEAR: '2015'
TRAIN_SENSOR: 'CrossMatch'
TEST_SENSOR: 'CrossMatch'
DATASET_PATH: './data'
BINARY_CLASS: true
TRANSFORM_TYPE: 'basic'
BATCH_SIZE: 8
NUM_WORKERS: 4
VALID_SPLIT: 0.1

# Model Configuration
MODEL_NAME: 'dual'
CRITERION_TYPE: 'bce_with_logits'
OPTIMIZER_TYPE: 'adam'
LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.0001
SCHEDULER_TYPE: 'cosine_annealing'
NUM_EPOCHS: 1

THRESHOLD: 0.5
WANDB_API_KEY: ''
MODEL_SAVE_PATH: './ckpts/classic_model.pth'